# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
