# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171023_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal4_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('beforeMarry', models.IntegerField()),
                ('partnerDA', models.IntegerField()),
                ('partnerName', models.CharField(max_length=20)),
                ('childName', models.CharField(max_length=20)),
                ('parentName', models.CharField(max_length=20)),
                ('broName', models.CharField(max_length=20)),
                ('gPaName', models.CharField(max_length=20)),
                ('estate', models.IntegerField()),
                ('successName', models.CharField(max_length=20)),
                ('spendEnd', models.IntegerField()),
                ('successName2', models.CharField(max_length=20)),
                ('spendEnd2', models.IntegerField()),
            ],
        ),
    ]
