# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cal4_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal4_ans',
            name='beforeMarry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cal4_ans',
            name='estate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cal4_ans',
            name='partnerDA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cal4_ans',
            name='spendEnd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cal4_ans',
            name='spendEnd2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cal4_ans',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
