# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171106_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal4_ans',
            name='broNum',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cal4_ans',
            name='childNum',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cal4_ans',
            name='gPaNum',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cal4_ans',
            name='parentNum',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
